export const itensChecklist = [
    '1. Conferir o escoamento da linha',
    '2. Documento de linha',
    '3. Layout',
    '4. Ajustar bancadas conforme o layout',
    '5. Cabo de rede',
    '6. Scanner de qr code ou barra',
    '7. Mouses',
    '8. Teclados',
    '9. Parafusadeira',
    '10. Soprador',
    '11. Verificar se as bancadas estão corretas',
    '12. Ligar todas as bancadas',
    '13. Verificar as mantas das bancadas',
    '14. Verificar os fios de aterramentos',
    '15. Seladora',
    '16. Balança',
    '17. Monitor',
    '18. Notebook',
    '19. CPUs',
    '20. Máquinas Laser',
    '21. Ionizador',
    '22. Conferir o funcionamento de todos os equipamentos abastecidos',
    '23. Conferir estruturação da linha',
    '24. Recolher equipamentos que não estão no layout ou no proceso',
    '25. Validação de 5S da linha junto ao monitor/lider',
    '26. Verificar postos críticos e instalar placas conforme a IT',
    '27. Conferir a instalação de mouse pads nas bancadas',
];