// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketSystem.API.Data;

#nullable disable

namespace TicketSystem.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TicketSystem.API.Models.ChecklistTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedRoles")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("allowed_roles");

                    b.Property<string>("CardColorHex")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("card_color_hex");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("icon_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("schema");

                    b.Property<string>("TriggerFieldId")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("trigger_field_id");

                    b.Property<string>("TriggerFieldValue")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("trigger_field_value");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_checklist_templates");

                    b.HasIndex("PlantId")
                        .HasDatabaseName("ix_checklist_templates_plant_id");

                    b.HasIndex("DepartmentId", "IsActive")
                        .HasDatabaseName("ix_checklist_templates_department_id_is_active");

                    b.ToTable("checklist_templates", (string)null);
                });

            modelBuilder.Entity("TicketSystem.API.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedRoles")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("allowed_roles");

                    b.Property<string>("Badges")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("badges");

                    b.Property<string>("CardColorHex")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("card_color_hex");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("FormSchema")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("form_schema");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("icon_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("PlantId")
                        .HasDatabaseName("ix_departments_plant_id");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("TicketSystem.API.Models.FieldTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("schema");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_field_templates");

                    b.HasIndex("PlantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_field_templates_plant_id_name");

                    b.ToTable("field_templates", (string)null);
                });

            modelBuilder.Entity("TicketSystem.API.Models.LinePrefix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("label");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_line_prefixes");

                    b.HasIndex("PlantId")
                        .HasDatabaseName("ix_line_prefixes_plant_id");

                    b.ToTable("line_prefixes", (string)null);
                });

            modelBuilder.Entity("TicketSystem.API.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_plants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_plants_slug");

                    b.ToTable("plants", (string)null);
                });

            modelBuilder.Entity("TicketSystem.API.Models.PlantConnector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("Panel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("panel");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.Property<string>("Prefix")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("prefix");

                    b.Property<int>("Source")
                        .HasColumnType("int")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_plant_connectors");

                    b.HasIndex("PlantId")
                        .HasDatabaseName("ix_plant_connectors_plant_id");

                    b.ToTable("plant_connectors", (string)null);
                });

            modelBuilder.Entity("TicketSystem.API.Models.ProductionLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("line_name");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("prefix");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_production_lines");

                    b.HasIndex("LineName")
                        .IsUnique()
                        .HasDatabaseName("ix_production_lines_line_name");

                    b.HasIndex("PlantId")
                        .HasDatabaseName("ix_production_lines_plant_id");

                    b.HasIndex("Prefix")
                        .HasDatabaseName("ix_production_lines_prefix");

                    b.ToTable("production_lines", (string)null);
                });

            modelBuilder.Entity("TicketSystem.API.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChecklistContent")
                        .HasColumnType("json")
                        .HasColumnName("checklist_content");

                    b.Property<int>("ChecklistStatus")
                        .HasColumnType("int")
                        .HasColumnName("checklist_status");

                    b.Property<int?>("ChecklistTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("checklist_template_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<string>("DynamicAnswers")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("dynamic_answers");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("finished_at");

                    b.Property<bool>("IsLineStopped")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_line_stopped");

                    b.Property<string>("LineStoppedTime")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("line_stopped_time");

                    b.Property<int>("MonitorId")
                        .HasColumnType("int")
                        .HasColumnName("monitor_id");

                    b.Property<string>("MonitorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("monitor_name");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.Property<int?>("ProductionLineId")
                        .HasColumnType("int")
                        .HasColumnName("production_line_id");

                    b.Property<string>("ResolutionFeedback")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("resolution_feedback");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int")
                        .HasColumnName("technician_id");

                    b.Property<string>("TechnicianName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("technician_name");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_tickets_department_id");

                    b.HasIndex("PlantId")
                        .HasDatabaseName("ix_tickets_plant_id");

                    b.HasIndex("ProductionLineId")
                        .HasDatabaseName("ix_tickets_production_line_id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("TicketSystem.API.Models.ChecklistTemplate", b =>
                {
                    b.HasOne("TicketSystem.API.Models.Plant", "Plant")
                        .WithMany("ChecklistTemplates")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_templates_plants_plant_id");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("TicketSystem.API.Models.Department", b =>
                {
                    b.HasOne("TicketSystem.API.Models.Plant", "Plant")
                        .WithMany("Departments")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_departments_plants_plant_id");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("TicketSystem.API.Models.FieldTemplate", b =>
                {
                    b.HasOne("TicketSystem.API.Models.Plant", "Plant")
                        .WithMany("FieldTemplates")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_field_templates_plants_plant_id");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("TicketSystem.API.Models.LinePrefix", b =>
                {
                    b.HasOne("TicketSystem.API.Models.Plant", "Plant")
                        .WithMany("LinePrefixes")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_line_prefixes_plants_plant_id");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("TicketSystem.API.Models.PlantConnector", b =>
                {
                    b.HasOne("TicketSystem.API.Models.Plant", "Plant")
                        .WithMany("PlantConnectors")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plant_connectors_plants_plant_id");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("TicketSystem.API.Models.ProductionLine", b =>
                {
                    b.HasOne("TicketSystem.API.Models.Plant", "Plant")
                        .WithMany("ProductionLines")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_lines_plants_plant_id");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("TicketSystem.API.Models.Ticket", b =>
                {
                    b.HasOne("TicketSystem.API.Models.Department", "Department")
                        .WithMany("Tickets")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_departments_department_id");

                    b.HasOne("TicketSystem.API.Models.Plant", "Plant")
                        .WithMany("Tickets")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_plants_plant_id");

                    b.HasOne("TicketSystem.API.Models.ProductionLine", "ProductionLine")
                        .WithMany("Tickets")
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_production_lines_production_line_id");

                    b.Navigation("Department");

                    b.Navigation("Plant");

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("TicketSystem.API.Models.Department", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketSystem.API.Models.Plant", b =>
                {
                    b.Navigation("ChecklistTemplates");

                    b.Navigation("Departments");

                    b.Navigation("FieldTemplates");

                    b.Navigation("LinePrefixes");

                    b.Navigation("PlantConnectors");

                    b.Navigation("ProductionLines");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketSystem.API.Models.ProductionLine", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
